---
# tasks file for git_repo

- name: update slave server
  command: apt update

- name: install git and git dependencies
  apt:
    name: git
    state: present

- name: print git version
  debug:
    msg: "The current version of git is {{git_version}}"

- name: Clone a github repository
  git: 
    dest: "{{PWD}}"
    repo: "{{git_repo_url}}"
    
#  - name: set least privillages for laravel www-data
#    command: chown -R :www-data "{{path_to_file}}"

# - name: set least privillages for laravel
#   command: chmod -R 775  "{{path_to_file}}""

# - name: et least privillages for laravel/storage
#   command: chmod -R 775  "{{path_to_file}}/storage"

# - name: set least privillages for laravel/bootstrap/cache
#   command: chmod -R 775  "{{path_to_file}}/bootstrap/cache"

# - name: set least privillages for laravel www-data
#   file:
#     path: "{{path_to_file}}"
#     state: directory
#     mode: "775"
#     owner: admin
#     become: true

# - name: set least privillages for laravel
#   file:
#     path: "{{path_to_file}}"
#     state: directory
#     mode: 775
#     recursive: yes
#     become: true

# - name: set least privillages for laravel/storage
#   file:
#     path: "{{path_to_file}}/storage"
#     state: directory
#     mode: 775
#     recursive: yes
#     become: true

# - name: set least privillages for laravel/bootstrap/cache
#   file:
#     path: "{{path_to_file}}/bootstrap/cache"
#     state: directory
#     mode: 775
#     recursive: yes
#     become: true
