---
# tasks file for php_config

- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install php8.1
  apt: name={{item}} state=installed
  with_items:
    - php8.1
    - libapache2-mod-php
    - php8.1-dev
    - php8.1-zip
    - php8.1-curl
    - php8.1-mbstring
    - php8.1-mysql
    - php8.1-gd
    - php8.1-xml

- name: ensure php8.1-fpm cgi.fix_pathinfo=0
  lineinfile: dest={{path_php_ini}}} regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
