---
# tasks file for php_config

- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600
  
- name: Add the packages in sources lists
  shell: sh -c "echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main"\| sudo tee /etc/apt/sources.list.d/sury-php.list"

- name: install gnupg
  command: apt install gnupg gnupg2 -y

- name: Download the signing key
  shell: wget -qO - https://packages.sury.org/php/apt.gpg | sudo apt-key add -
  
- name: install php
  command: apt install $ sudo apt-get install php8.1 libapache2-mod-php php8.1-dev php8.1-zip php8.1-curl php8.1-mbstring php8.1-mysql php8.1-gd php8.1-xml -php8.1-fpm php8.1-bcmaty -y 
  
# - name: Add Public key
#   shell: gpg --keyserver pgpkeys.mit.edu --recv-key B188E2B695BD4743
  
# - name: Update the apt cache
#   apt: update_cache=yes cache_valid_time=3600

# - name: install php8.1
#   apt: name="{{php_apt}}" state=present

#  - name: install packages
#     apt: name={{ item }} update_cache=yes state=present
#     with_items:
#       - {{php_apt}}

- name: ensure php8.1-fpm cgi.fix_pathinfo=0
  lineinfile: dest={{path_php_ini}}} regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
