---
# tasks file for php_config

- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600
  
- name: Add the packages in sources lists
  shell: sh -c "echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main"\| sudo tee /etc/apt/sources.list.d/sury-php.list"

- name: install gnupg
  command: apt install gnupg gnupg2 -y

- name: Download the signing key
  shell: wget -qO - https://packages.sury.org/php/apt.gpg | sudo apt-key add -
  
- name: Add Public key
  shell: gpg --keyserver pgpkeys.mit.edu --recv-key B188E2B695BD4743
  
- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install php8.1
  apt: name=["{{php_apt}}"] state=present

- name: ensure php8.1-fpm cgi.fix_pathinfo=0
  lineinfile: dest={{path_php_ini}}} regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
