---
# vars file for php_config

path_php_ini: /etc/php/8.1/apache2/php.ini

php_apt: ['php', 'libapache2-mod-php', 'php-dev', 'php-zip', 'php-curl', 'php-mbstring', 'php-mysql', 'php-gd', 'php-xml', 'php-fpm']

#php_apt: ['php8.1', 'libapache2-mod-php', 'php8.1-dev', 'php8.1-zip', 'php8.1-curl', 'php8.1-mbstring', 'php8.1-mysql', 'php8.1-gd', 'php8.1-xml', 'php8.1-fpm', 'php8.1-bcmat']
