---
# tasks file for playbook
- name: update slave server
  apt:
    name: "*"
    state: latest

- name: install apache2
  apt:
    name: apache2
    state: latest

- name: print apache2 version
    debug:
      msg: "The current version of apache2 is {{apache2_version}}"

- name: install git and git dependencies
  apt:
    name: git
    state: latest

- name: print git version
    debug:
      msg: "The current version of git is {{git_version}}"

- name: Clone a github repository
    git:
      repo: "{{git_repo_url}}"
      dest: "{{PWD}}"
      clone: yes
      update: yes

- name: Update the apt cache
    apt: update_cache=yes cache_valid_time=3600

- name: Add the packages in sources lists
    shell: sh -c "echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main"\
      | sudo tee /etc/apt/sources.list.d/sury-php.list"
    when: ansible_os_family == 'Debian'

- name: install gnupg
  command: apt install gnupg gnupg2

- name: Download the signing key
    shell: wget -qO - https://packages.sury.org/php/apt.gpg | sudo apt-key add -

- name: Update the apt cache
    apt: update_cache=yes cache_valid_time=3600


